// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aojvmxusgctdscchzbuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvanZteHVzZ2N0ZHNjY2h6YnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MjA0MzQsImV4cCI6MjA1NDQ5NjQzNH0.hZ9ePl5315wbZYlwfR3FgyRTVP1IVjsfCpLq8HNwMAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);