// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhpuvcolekfrvvcypgdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocHV2Y29sZWtmcnZ2Y3lwZ2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MTk4MTUsImV4cCI6MjA1NDQ5NTgxNX0.M6biIvgBUZ-gX9NRePCh835MSSvM0x3ZyZxu_eV3aRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);